name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}_${{ github.head_ref }}
        path:  ${{ github.workspace }}/
